print("elo1")
print("elo2")
print("elo2")
print("elo2")
print("elo2")
print("elo2")
print("siema siem ")
print("testowanie nie jest takie złe")
print("elo1")
print("elo2")
print("elo2")
print("elo2")
print("elo2")
print("elo2")
print("siema siem ")
print("testowanie nie jest takie złe")
